import React from 'react';
import ReactMarkdown from 'react-markdown';
import { MessageCircle, ExternalLink } from 'lucide-react';
import Link from 'next/link';

export default function ChatMessage({ role, content, onFollowUpClick }) {
  const isUser = role === 'user';
  const isSystem = role === 'system';

  // Return empty for purely structural messages if any
  if (isSystem) return null;

  // Regex to extract special UI markers generated by AI
  const actionRegex = /\[ACTION:(.*?):(.*?)\]/g;
  const followupRegex = /\[FOLLOWUP:(.*?)\]/g;
  
  const actions = [];
  let match;
  while ((match = actionRegex.exec(content)) !== null) {
    actions.push({ type: match[1], id: match[2] });
  }
  
  const followups = [];
  while ((match = followupRegex.exec(content)) !== null) {
    followups.push(match[1]);
  }
  
  // Clean text for Markdown rendering
  const cleanContent = content.replace(actionRegex, '').replace(followupRegex, '').trim();

  return (
    <div className={`flex w-full mb-4 ${isUser ? 'justify-end' : 'justify-start'}`}>
      {!isUser && (
        <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-[#E91E63] to-[#C2185B] flex items-center justify-center text-white shrink-0 mr-3 shadow-md">
          <MessageCircle className="w-4.5 h-4.5" />
        </div>
      )}
      <div className={`max-w-[85%] px-4 py-3 text-[14px] ${
        isUser 
          ? 'bg-[#E91E63] text-white rounded-2xl rounded-br-sm shadow-md' 
          : 'bg-white border border-[#F8BBD0]/40 text-gray-700 rounded-2xl rounded-bl-sm shadow-sm'
      }`}>
        <div className={`prose prose-sm max-w-none prose-p:leading-relaxed prose-headings:font-bold break-words ${isUser ? 'prose-invert text-white' : 'prose-a:text-[#E91E63]'}`}>
          <ReactMarkdown>{cleanContent}</ReactMarkdown>
        </div>
        
        {/* Render Action Buttons */}
        {actions.length > 0 && (
          <div className="mt-3 flex flex-wrap gap-2 pt-2 border-t border-gray-100">
            {actions.map((action, idx) => {
              if (action.type === 'VIEW') {
                return (
                  <Link key={idx} href={`/products/${action.id}`} className="btn-outline px-3 py-1.5 text-xs font-bold rounded-xl border-[#F8BBD0] text-[#E91E63] hover:bg-pink-50 flex items-center gap-1.5 shadow-sm transition-all">
                    <ExternalLink className="w-3.5 h-3.5" /> View Product
                  </Link>
                )
              }
              return null;
            })}
          </div>
        )}

        {/* Render Follow-ups */}
        {followups.length > 0 && onFollowUpClick && (
          <div className="mt-3 flex flex-wrap gap-1.5 pt-2 border-t border-gray-100">
            {followups.map((prompt, idx) => (
              <button
                key={idx}
                onClick={() => onFollowUpClick(prompt)}
                className="text-left bg-pink-50 hover:bg-pink-100 text-[#E91E63] border border-pink-200/60 rounded-xl px-3 py-1.5 text-[11px] font-bold transition-colors flex items-center gap-1.5 shadow-sm"
              >
                <span className="shrink-0 w-1.5 h-1.5 rounded-full bg-[#E91E63]/60" /> {prompt}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
